services:
  hmpps-auth:
    ports:
      - "9090:9090"

  coordinator-api:
    ports:
      - "8070:8080"

  san-api:
    ports:
      - "8080:8080"

  san-ui:
    ports:
      - "3000:3000"

  arns-handover:
    ports:
      - "7070:7070"

  aap-ui:
    ports:
      - "7072:3000"

  localstack:
    ports:
      - "4566:4566"
